export const CHUNK_AXIS_ORDER = 'zxy'
export const PATCH_SIZE = 64
export const CHUNK_SIZE = { xz: PATCH_SIZE, y: PATCH_SIZE };
export const CHUNKS_RANGE = { bottom: 0, top: 5 }
export const WORLD_ALTITUDE_RANGE = { min: -1, max: 400 }
export const CAMERA_MIN_DISTANCE = 0.001
export const CAMERA_DISTANCE_STEP = 1
export const CAMERA_MAX_DISTANCE = 4000
export const PLAYER_SPEED = 20
export const VIEW_DIST = 400